# Generated by Django 3.0.5 on 2020-04-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20200417_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonlisting',
            old_name='site',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='amazonparentlisting',
            old_name='site',
            new_name='domain',
        ),
    ]
