# Generated by Django 3.0.5 on 2020-04-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200418_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonlisting',
            old_name='market_price',
            new_name='original_price',
        ),
    ]
