# Generated by Django 3.0.5 on 2020-04-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=32, unique=True)),
                ('parent_asin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('url', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('variation_specifics', models.CharField(blank=True, max_length=255, null=True)),
                ('review_count', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('avg_rating', models.FloatField(blank=True, default=0, null=True)),
                ('is_fba', models.BooleanField(default=0)),
                ('is_addon', models.BooleanField(default=0)),
                ('is_pantry', models.BooleanField(default=0)),
                ('has_sizechart', models.BooleanField(default=0)),
                ('international_shipping', models.BooleanField(default=0)),
                ('merchant_id', models.CharField(blank=True, max_length=32, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_listings',
            },
        ),
        migrations.CreateModel(
            name='AmazonListingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=32)),
                ('picture_url', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_listing_pictures',
            },
        ),
    ]
