# Generated by Django 3.0.5 on 2020-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200416_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlisting',
            name='site',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amazonparentlisting',
            name='site',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
