# Generated by Django 3.0.5 on 2020-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_amazonlistingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlistingprice',
            name='domain',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
