# Generated by Django 3.0.5 on 2020-05-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_amazonlistingprice_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonlisting',
            name='asin',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='amazonlisting',
            name='domain',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='amazonlistingprice',
            name='domain',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='amazonparentlisting',
            name='domain',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='amazonparentlisting',
            name='parent_asin',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='amazonparentlisting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='amazonlisting',
            constraint=models.UniqueConstraint(fields=('asin', 'domain'), name='unique_asin_domain'),
        ),
        migrations.AddConstraint(
            model_name='amazonlistingprice',
            constraint=models.UniqueConstraint(fields=('asin', 'domain'), name='unique_asin_price_domain'),
        ),
        migrations.AddConstraint(
            model_name='amazonparentlisting',
            constraint=models.UniqueConstraint(fields=('parent_asin', 'domain'), name='unique_parent_asin_domain'),
        ),
    ]
