# Generated by Django 3.0.5 on 2020-05-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_rawdata_http_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonListing',
        ),
        migrations.DeleteModel(
            name='AmazonListingPrice',
        ),
        migrations.DeleteModel(
            name='AmazonParentListing',
        ),
    ]
