# Generated by Django 3.0.5 on 2020-05-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20200510_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
