# Generated by Django 3.0.7 on 2020-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_rawdata_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=32)),
                ('sku', models.CharField(db_index=True, max_length=32)),
                ('title', models.TextField()),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resrc_items',
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=32)),
                ('sku', models.CharField(db_index=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('store_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resrc_item_prices',
            },
        ),
    ]
