# Generated by Django 3.0.7 on 2020-06-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_item_upc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
