# Generated by Django 3.0.7 on 2020-06-05 16:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_auto_20200605_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemprice',
            name='store_location',
        ),
        migrations.AddField(
            model_name='itemprice',
            name='online_availability',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='online_urgent_quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='store_availabilities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
