# Generated by Django 3.0.7 on 2020-06-19 22:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_item_parent_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
