# common settings across packages

BOT_PROJECT = 'pricewatch_bot'
BOT_VERISON = '0.0.1'

WEB_PROJECT = 'pricewatch_web'
WEB_VERISON = '0.0.1'

SCHEDULAR_PROJECT = 'pricewatch_schedular'
SCHEDULAR_VERSION = '0.0.1'

APP_DATA_DIRPATH = '/usr/local/etc/pricewatch/'
APP_DIST_DIRPATH = APP_DATA_DIRPATH + 'dist/'
APP_CONFIG_FILEPATH = APP_DATA_DIRPATH + 'pricewatch.ini'

# django model statuses
SCHEDULES_JOB_STATUS_CANCELED = 0
SCHEDULES_JOB_STATUS_PENDING = 1
SCHEDULES_JOB_STATUS_RUNNING = 2
SCHEDULES_JOB_STATUS_FINISHED = 3

SCHEDULES_VERSION_STATUS_DELETED = 0
SCHEDULES_VERSION_STATUS_ADDED = 1

RESOURCES_AMAZONLISTING_STATUS_INACTIVE = 0
RESOURCES_AMAZONLISTING_STATUS_ACTIVE = 1
