# Generated by Django 3.0.5 on 2020-05-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_project_version'),
        ),
    ]
