# Generated by Django 3.0.6 on 2020-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20200502_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
